### ISSUE TITLE
Make dot color dependent whether consensus has been achieved for an annotation

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/AnnoTate#36]
Issue is how to communicate to the user when consensus has been achieved for a particular annotation. Potential solution below:

![](http://i.imgur.com/XF2paZ2.png)

**Comment by ggdhines** [comment]
I like this idea but we need to decide exactly what we mean by "consensus". Is it enough that a minimum number of people have seen transcribed a line (say 5) or do we require that the aggregated transcription be of a certain quality. For example, if the aggregate transcription is at least 50% the length of the average individual transcriptions. 
I like the first way better because it will make things simpler for me. Also, if 5 people have already looked at a line and good aggregate transcriptions has not been achieved, then it is probably a hard line in need of an expert and not a good use of volunteer time. 
Either way, this will require accessing the results of the aggregation which I don't know if we have a plan for doing. @camallen or @edpaget might want to weigh in on how to do this.
I think this also argues in favour of using a line (or multi-line) to show exactly what text each set of markings corresponds to. For example, there is some inserted text on the 4th line (^ something ... tion). Regardless of how we want that text treated (so if it should be in its own separate transcription), we need to deal with how users actually transcribed it. If someone sees the above example, they might think that part of the text has not been transcribed. @rogerhutchings @VVH - thoughts?

**Comment by rogerhutchings** [comment]
Fixed via 4912c4d6e5e5a216ef15575d385560a2021fe4e8
