### ISSUE TITLE
Tutorial won't open

### ISSUE THREAD

**Issue by VVH** [zooniverse/AnnoTate#70]
Several users found that the tutorial didn't open. I assume this was in browsers other than Chrome.

**Comment by rogerhutchings** [comment]
It works in Chrome, FF and Safari - we need a Windows machine around for testing IE, really.

**Comment by eatyourgreens** [comment]
I've got a bunch of (slightly old) VMs from modern.ie if you need something tested quickly.

**Comment by rogerhutchings** [comment]
I'd forgotten about modern.ie - I can download them now. How far back do we need to support @eatyourgreens?

**Comment by eatyourgreens** [comment]
Probably IE9 or 10. Found out yesterday that NHM mostly runs IE8 internally, so lots of 'All I get is a black screen' from people visiting orchidobservers.org

**Comment by rogerhutchings** [comment]
Shouldn't we be stating outright which browsers we support?

**Comment by eatyourgreens** [comment]
For OWD I did a bunch of try/catch blocks with a generic "your browser is not supported" modal dialog.
https://github.com/zooniverse/Diaries/blob/master/app/main.coffee
OWD worked in IE8 when we launched it. I think somewhere along the line, jQuery dropped IE8 support so that went away in an update. Much prefer to test for code support than track browser versions.
